CREATE TABLE "GCG_6681_INV_SIMPART"(
 "ID" IDENTITY DEFAULT '0',
 "PART" CHAR(20) NOT NULL ,
 "PARTSIM" CHAR(20),
 UNIQUE ("ID"));

CREATE INDEX "GCG_INV_SIMPARTK00" USING 1 ON "GCG_6681_INV_SIMPART"("PART");
CREATE INDEX "GCG_INV_SIMPARTK01" USING 2 ON "GCG_6681_INV_SIMPART"("PARTSIM");